language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy-5.3
  - pypy3
  - pypy3.3-5.2-alpha1
  - nightly

matrix:
  allow_failures:
    - python: nightly
  include:
    - python: 2.7
      env: SCA=true
    - python: 3.5
      env: SCA=true

install:
  - if [ -z "$SCA" ]; then pip install --quiet coveralls; else echo skip; fi
  - if [ -n "$SCA" ]; then python setup.py develop; else echo skip; fi

script:
  - if [ -n "$SCA" ]; then yapf --diff --recursive . || exit; else echo skip; fi
  - if [ -z "$SCA" ]; then nosetests --with-coverage --cover-package=yapf; else echo skip; fi

after_success:
  - coveralls
